global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "django"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "172.17.0.1:8080"
          
  - job_name: "otel-collector"
    static_configs:
      - targets: ["172.17.0.1:9464"]
